---
micronaut:
    application:
        name: authapp
---
#micronaut:
#  security:
#    enabled: true
#    endpoints:
#      login:
#        enabled: true
#      oauth:
#        enabled: true
#    token:
#      jwt:
#        enabled: true
#        signatures:
#          secret:
#            generator:
#              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:b2a2734e81d044a4cc6ced937d6d935c60558e5b}"
#---
#mongodb:
#    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/demo"
#    options:
#        maxConnectionIdleTime: 10000

---
datasources.default: {}
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update